/**
 * DaemonSets.
 *
 * Two departures from the React original, both of which it got wrong:
 *
 * - **Status is a word, not a ratio.** `utils/daemonSetStatus.ts` returned
 *   `"2 / 3"` as the *status string* and hued it. That is the Ready column's job, and it
 *   left the DaemonSet-specific failure — pods running on nodes the selector no longer
 *   matches, i.e. `numberMisscheduled` — with nowhere to appear at all. A DaemonSet whose
 *   selector was edited reads as perfectly healthy in the React table.
 * - **There is no Scale action.** A DaemonSet has no `spec.replicas`; its replica count
 *   *is* the number of matching nodes. `api/k8s/daemonSets.ts` exports `scaleDaemonSet`
 *   and the backend registers `scale_daemon_set` — both generated by the macro that also
 *   covers Deployments — and calling either would patch a field the apiserver does not
 *   recognise on this kind. It is deliberately not wired up here. To change how many pods
 *   a DaemonSet runs you edit `spec.template.spec.nodeSelector`, which is what the Node
 *   selector column and the Pod template section are for.
 */

import { For, Show } from 'solid-js';
import { RotateCw, Server } from 'lucide-solid';
import type { V1Container, V1DaemonSet, V1OwnerReference } from '@kubernetes/client-node';

import {
  deleteDaemonSets,
  listDaemonSets,
  restartDaemonSet,
  updateDaemonSet,
  watchDaemonSets,
} from '@/api/k8s/daemonSets';
import type { K8sStatus } from '@/types/k8sStatus';
import { StatusBadge } from '@/ui/StatusBadge';
import { toast } from '@/ui/Toast';

import {
  AgeCell,
  ConditionsTable,
  DetailGrid,
  DetailRow,
  LabelList,
  ageValue,
} from '../detail-parts';
import { confirmRestart } from '../scale-dialog';
import { defineResource } from '../types';

/* -------------------------------------------------------------------------- */
/* Status                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * The state to show in the Status column.
 *
 * The hue mapping is the one from `utils/daemonSetStatus.ts` — all ready is `success`,
 * some ready is `warning`, none ready is `error`. What is new is that the three states a
 * ratio cannot express get to override it:
 *
 * - `desiredNumberScheduled === 0` is not a failure. It means the node selector matches
 *   nothing, which on a mixed-OS cluster is the normal state of half the DaemonSets in
 *   `kube-system`. The React version hued it `default` but still printed `0 / 0`, which
 *   reads as broken.
 * - `updatedNumberScheduled < desired` is a rollout in progress. Pods are ready, but they
 *   are not the pods the spec asks for.
 * - `numberMisscheduled > 0` means pods are running where they should not be. Nothing
 *   else on the screen says so.
 *
 * Written with plain field reads and no allocation: this runs per row per sort.
 */
export const getDaemonSetStatus = (daemonSet: V1DaemonSet): K8sStatus => {
  const status = daemonSet.status;
  const desired = status?.desiredNumberScheduled ?? 0;
  const ready = status?.numberReady ?? 0;

  if (desired === 0) return { status: 'No nodes matched', variant: 'secondary' };
  if (ready === 0) return { status: 'Unavailable', variant: 'error' };
  if (ready < desired) return { status: 'Progressing', variant: 'warning' };

  // Compared only when the field is present: `updatedNumberScheduled` is optional, and
  // treating a missing value as 0 would report a permanent rollout on any apiserver that
  // does not send it.
  const updated = status?.updatedNumberScheduled;
  if (updated !== undefined && updated < desired) {
    return { status: 'Rolling out', variant: 'warning' };
  }

  if ((status?.numberMisscheduled ?? 0) > 0) return { status: 'Misscheduled', variant: 'warning' };

  return { status: 'Available', variant: 'success' };
};

/* -------------------------------------------------------------------------- */
/* Detail helpers                                                             */
/* -------------------------------------------------------------------------- */

const ownerSummary = (owners?: V1OwnerReference[]): string | undefined =>
  owners?.map((owner) => `${owner.kind}/${owner.name}`).join(', ');

const quantitySummary = (quantities?: { [key: string]: string }): string | undefined => {
  const entries = Object.entries(quantities ?? {});
  if (entries.length === 0) return undefined;
  return entries.map(([key, value]) => `${key} ${value}`).join(' · ');
};

const portSummary = (container: V1Container): string | undefined => {
  const ports = container.ports ?? [];
  if (ports.length === 0) return undefined;
  return ports.map((port) => `${port.containerPort}/${port.protocol ?? 'TCP'}`).join(', ');
};

/**
 * `key=value` pairs of the pod template's node selector, as one string.
 *
 * Feeds the column's `value`, which is why it is not a `LabelList`: chips in a 28px row
 * would mean one Kobalte tooltip root per label per visible row, the cost `StatusBadge`
 * documents avoiding. The column is `sortable: false`, so this is only ever called when
 * the search box is used — the full set is in the Pod template section either way.
 */
const nodeSelectorSummary = (daemonSet: V1DaemonSet): string | undefined => {
  const selector = daemonSet.spec?.template.spec?.nodeSelector;
  if (!selector) return undefined;
  const entries = Object.entries(selector);
  if (entries.length === 0) return undefined;
  return entries.map(([key, value]) => `${key}=${value}`).join(', ');
};

const strategySummary = (daemonSet: V1DaemonSet): string | undefined => {
  const strategy = daemonSet.spec?.updateStrategy;
  if (!strategy?.type) return undefined;
  if (strategy.type !== 'RollingUpdate') return strategy.type;

  const unavailable = strategy.rollingUpdate?.maxUnavailable ?? 1;
  const surge = strategy.rollingUpdate?.maxSurge;
  const surgePart = surge === undefined ? '' : `, max surge ${surge}`;
  return `RollingUpdate (max unavailable ${unavailable}${surgePart})`;
};

const selectorSummary = (daemonSet: V1DaemonSet): string | undefined => {
  const expressions = daemonSet.spec?.selector?.matchExpressions;
  if (!expressions || expressions.length === 0) return undefined;
  return expressions
    .map((expression) =>
      `${expression.key} ${expression.operator} ${expression.values?.join(',') ?? ''}`.trim()
    )
    .join(', ');
};

/**
 * Tolerations as `key operator value : effect`.
 *
 * Worth a row on this kind specifically: a DaemonSet that is expected to run on control
 * plane or tainted nodes and does not is almost always a missing toleration, and there is
 * nowhere else in the app to see them.
 */
const tolerationSummary = (daemonSet: V1DaemonSet): string | undefined => {
  const tolerations = daemonSet.spec?.template.spec?.tolerations;
  if (!tolerations || tolerations.length === 0) return undefined;
  return tolerations
    .map((toleration) => {
      const key = toleration.key ?? '*';
      const operator = toleration.operator ?? 'Equal';
      const value = toleration.value ? ` ${toleration.value}` : '';
      const effect = toleration.effect ? ` : ${toleration.effect}` : '';
      return `${key} ${operator}${value}${effect}`;
    })
    .join(', ');
};

const volumeNames = (daemonSet: V1DaemonSet): string | undefined => {
  const volumes = daemonSet.spec?.template.spec?.volumes;
  if (!volumes || volumes.length === 0) return undefined;
  return volumes.map((volume) => volume.name).join(', ');
};

/**
 * Init container names, as one line.
 *
 * Named rather than expanded into cards: node-level DaemonSets routinely use an init
 * container only to copy a binary onto the host, and a full card per one of those pushes
 * the container that does the work off the screen. The Pods screen shows their state.
 */
const initContainerNames = (daemonSet: V1DaemonSet): string | undefined => {
  const containers = daemonSet.spec?.template.spec?.initContainers;
  if (!containers || containers.length === 0) return undefined;
  return containers.map((container) => container.name).join(', ');
};

/* -------------------------------------------------------------------------- */
/* Descriptor                                                                 */
/* -------------------------------------------------------------------------- */

export const daemonSetsDescriptor = defineResource({
  id: 'daemonSets',
  kind: 'DaemonSet',
  title: 'DaemonSets',
  group: 'workloads',
  icon: Server,
  namespaced: true,

  api: {
    list: listDaemonSets,
    watch: watchDaemonSets,
    remove: deleteDaemonSets,
    update: updateDaemonSet,
  },

  status: getDaemonSetStatus,

  searchExtra: (daemonSet: V1DaemonSet) => [
    ...Object.entries(daemonSet.metadata?.labels ?? {}).map(([key, value]) => `${key}=${value}`),
    ...(daemonSet.spec?.template.spec?.containers ?? []).map((container) => container.image),
  ],

  columns: [
    {
      id: 'name',
      header: 'Name',
      width: 'minmax(160px, 2fr)',
      value: (daemonSet: V1DaemonSet) => daemonSet.metadata?.name,
    },
    {
      id: 'namespace',
      header: 'Namespace',
      width: 'minmax(100px, 1.2fr)',
      value: (daemonSet: V1DaemonSet) => daemonSet.metadata?.namespace,
    },
    {
      id: 'desired',
      header: 'Desired',
      width: '60px',
      align: 'right',
      value: (daemonSet: V1DaemonSet) => daemonSet.status?.desiredNumberScheduled ?? 0,
    },
    {
      id: 'current',
      header: 'Current',
      width: '60px',
      align: 'right',
      value: (daemonSet: V1DaemonSet) => daemonSet.status?.currentNumberScheduled ?? 0,
    },
    {
      id: 'ready',
      header: 'Ready',
      width: '56px',
      align: 'right',
      value: (daemonSet: V1DaemonSet) => daemonSet.status?.numberReady ?? 0,
    },
    {
      id: 'uptodate',
      header: 'Up-to-date',
      width: '80px',
      align: 'right',
      value: (daemonSet: V1DaemonSet) => daemonSet.status?.updatedNumberScheduled ?? 0,
    },
    {
      id: 'available',
      header: 'Available',
      width: '72px',
      align: 'right',
      value: (daemonSet: V1DaemonSet) => daemonSet.status?.numberAvailable ?? 0,
    },
    {
      id: 'nodeSelector',
      header: 'Node selector',
      width: 'minmax(100px, 1.4fr)',
      // Not sortable: the value is a derived string, and sorting would call the join
      // above per row per comparison. Nobody sorts by node selector; people search it.
      sortable: false,
      value: (daemonSet: V1DaemonSet) => nodeSelectorSummary(daemonSet),
    },
    {
      id: 'status',
      header: 'Status',
      width: 'minmax(100px, 1.2fr)',
      value: (daemonSet: V1DaemonSet) => getDaemonSetStatus(daemonSet).status,
      cell: (daemonSet: V1DaemonSet) => {
        const status = getDaemonSetStatus(daemonSet);
        return <StatusBadge status={status.status} variant={status.variant} size="sm" />;
      },
    },
    {
      id: 'age',
      header: 'Age',
      width: '68px',
      align: 'right',
      value: (daemonSet: V1DaemonSet) => ageValue(daemonSet),
      cell: (daemonSet: V1DaemonSet) => (
        <AgeCell timestamp={daemonSet.metadata?.creationTimestamp} />
      ),
    },
  ],

  detail: [
    {
      id: 'metadata',
      title: 'Metadata',
      render: (daemonSet: V1DaemonSet) => (
        <DetailGrid>
          <DetailRow label="Name">{daemonSet.metadata?.name}</DetailRow>
          <DetailRow label="Namespace">{daemonSet.metadata?.namespace}</DetailRow>
          <DetailRow label="Created">
            <AgeCell timestamp={daemonSet.metadata?.creationTimestamp} /> ago
          </DetailRow>
          <DetailRow label="Generation">{daemonSet.metadata?.generation}</DetailRow>
          <DetailRow label="Controlled by">
            {ownerSummary(daemonSet.metadata?.ownerReferences)}
          </DetailRow>
          <DetailRow label="Labels">
            <LabelList entries={daemonSet.metadata?.labels} />
          </DetailRow>
          <DetailRow label="Annotations">
            <LabelList entries={daemonSet.metadata?.annotations} />
          </DetailRow>
        </DetailGrid>
      ),
    },
    {
      id: 'scheduling',
      title: 'Pods',
      render: (daemonSet: V1DaemonSet) => (
        <DetailGrid>
          <DetailRow label="Desired">{daemonSet.status?.desiredNumberScheduled ?? 0}</DetailRow>
          <DetailRow label="Current">{daemonSet.status?.currentNumberScheduled ?? 0}</DetailRow>
          <DetailRow label="Ready">{daemonSet.status?.numberReady ?? 0}</DetailRow>
          <DetailRow label="Up-to-date">{daemonSet.status?.updatedNumberScheduled ?? 0}</DetailRow>
          <DetailRow label="Available">{daemonSet.status?.numberAvailable ?? 0}</DetailRow>
          <DetailRow label="Unavailable">{daemonSet.status?.numberUnavailable ?? 0}</DetailRow>
          <DetailRow
            label="Misscheduled"
            // Hued only when it is non-zero: a red 0 would be a permanent false alarm.
            class={
              (daemonSet.status?.numberMisscheduled ?? 0) > 0
                ? 'text-[var(--status-warn)]'
                : undefined
            }
          >
            {daemonSet.status?.numberMisscheduled ?? 0}
          </DetailRow>
          <DetailRow label="Min ready">{daemonSet.spec?.minReadySeconds ?? 0}s</DetailRow>
        </DetailGrid>
      ),
    },
    {
      id: 'strategy',
      title: 'Update strategy',
      render: (daemonSet: V1DaemonSet) => (
        <DetailGrid>
          <DetailRow label="Type">{strategySummary(daemonSet)}</DetailRow>
          <DetailRow label="Revision limit">{daemonSet.spec?.revisionHistoryLimit}</DetailRow>
          <DetailRow label="Collisions">{daemonSet.status?.collisionCount}</DetailRow>
        </DetailGrid>
      ),
    },
    {
      id: 'selector',
      title: 'Selector',
      render: (daemonSet: V1DaemonSet) => (
        <DetailGrid>
          <DetailRow label="Match labels">
            <LabelList entries={daemonSet.spec?.selector?.matchLabels} />
          </DetailRow>
          <DetailRow label="Expressions">{selectorSummary(daemonSet)}</DetailRow>
        </DetailGrid>
      ),
    },
    {
      id: 'template',
      title: 'Pod template',
      render: (daemonSet: V1DaemonSet) => (
        <div class="flex flex-col gap-2">
          <DetailGrid>
            <DetailRow label="Labels">
              <LabelList entries={daemonSet.spec?.template.metadata?.labels} />
            </DetailRow>
            <DetailRow label="Service account">
              {daemonSet.spec?.template.spec?.serviceAccountName}
            </DetailRow>
            <DetailRow label="Node selector">
              <LabelList entries={daemonSet.spec?.template.spec?.nodeSelector} empty="Every node" />
            </DetailRow>
            <DetailRow label="Tolerations">{tolerationSummary(daemonSet)}</DetailRow>
            <DetailRow label="Host network">
              {daemonSet.spec?.template.spec?.hostNetwork ? 'Yes' : 'No'}
            </DetailRow>
            <DetailRow label="Priority class">
              {daemonSet.spec?.template.spec?.priorityClassName}
            </DetailRow>
            <DetailRow label="Volumes">{volumeNames(daemonSet)}</DetailRow>
          </DetailGrid>

          <For each={daemonSet.spec?.template.spec?.containers}>
            {(container) => (
              <div class="rounded-sm border border-[var(--border-subtle)] bg-[var(--surface-inset)] p-2">
                <div class="selectable mb-1.5 truncate font-medium text-[var(--text-primary)]">
                  {container.name}
                </div>
                <DetailGrid>
                  <DetailRow label="Image">{container.image}</DetailRow>
                  <DetailRow label="Ports">{portSummary(container)}</DetailRow>
                  <DetailRow label="Requests">
                    {quantitySummary(container.resources?.requests)}
                  </DetailRow>
                  <DetailRow label="Limits">
                    {quantitySummary(container.resources?.limits)}
                  </DetailRow>
                </DetailGrid>
              </div>
            )}
          </For>

          <Show when={initContainerNames(daemonSet)}>
            {(names) => (
              <div class="text-2xs text-[var(--text-tertiary)]">Init containers: {names()}</div>
            )}
          </Show>
        </div>
      ),
    },
    {
      id: 'conditions',
      title: 'Conditions',
      render: (daemonSet: V1DaemonSet) => (
        <ConditionsTable conditions={daemonSet.status?.conditions} />
      ),
    },
  ],

  actions: [
    {
      id: 'restart',
      label: 'Restart',
      icon: RotateCw,
      // A rolling restart of ten DaemonSets at once is never what someone meant to ask
      // for, and there is no undo.
      multi: false,
      run: async (items: V1DaemonSet[], ctx) => {
        const daemonSet = items[0];
        const name = daemonSet?.metadata?.name;
        if (!name) return;

        const confirmed = await confirmRestart(
          name,
          'Every pod is replaced, one node at a time. A DaemonSet usually runs node-level infrastructure — logging, CNI, storage — so expect a gap in whatever this one provides.'
        );
        if (!confirmed) return;

        await restartDaemonSet({
          name: ctx.context,
          namespace: daemonSet?.metadata?.namespace,
          resourceName: name,
        });
        // No refetch: the patched `spec.template.metadata.annotations` comes back as a
        // MODIFIED watch event, and the rollout follows on the pods screen.
        toast.success(`Restarting ${name}`);
      },
    },
  ],
});
